# Standalone emission (DESIGN.md D10; M6): the same module the runtime mode
# builds, with a prologue that imports only the standard library and core's
# pure helpers — never the compiler, never `ecma_regex` (patterns are
# emitted pre-translated for `re`). Anything that would need the
# interpreter at evaluation time (an island, an unlicensed consumer, a
# cycle) is refused rather than emitted as a module that would quietly
# disagree with `Engine.evaluate`.
#
# Dependency direction: imports the planner, serializer, `emit`, core's
# engine façade and errors, and `ecma_regex`'s translator. The public API
# imports this.

import ast
import importlib

import ecma_regex
from json_schema_engine.compiler import emit as e
from json_schema_engine.compiler.errors import StandaloneUnsupportedError
from json_schema_engine.compiler.plan import (
    DEFAULT_MAX_DYNAMIC_WINNERS,
    build_plan_over,
    explain_compilation,
)
from json_schema_engine.compiler.serialize import (
    DEFAULT_FLAGS,
    assemble,
    serialize_plan,
)
from json_schema_engine.core.engine import Engine

HEADER = (
    "# Generated by json_schema_engine.compiler (standalone mode). Imports only\n"
    "# the standard library, json_schema_engine.core's pure helpers, and (when\n"
    "# the schema asserts formats) predicates from json_schema_engine.formats;\n"
    "# the compiler package is not needed to import or run this module. The\n"
    "# 'idna' extra must be installed where this runs if idn formats are used.\n"
)


def _import_from(module: str, names: list[tuple[str, str | None]]) -> ast.ImportFrom:
    return ast.ImportFrom(
        module=module,
        names=[ast.alias(name=name, asname=asname) for name, asname in names],
        level=0,
    )


def _pattern_source(engine: Engine, source: str) -> tuple[str, int]:
    """The `re` pattern and flags for a schema pattern under the engine's
    regex dialect: translated from ECMA-262, or verbatim under `python`."""
    if engine.regex_cache.dialect == "python":
        return source, 0
    parsed = ecma_regex.parse(source)
    return ecma_regex.translate(parsed, backend="re"), ecma_regex.translate_flags(
        parsed
    )


def emit_standalone(
    engine: Engine,
    schema_uri: str,
    *,
    max_depth: int | None = None,
    max_dynamic_winners: int = DEFAULT_MAX_DYNAMIC_WINNERS,
) -> str:
    """Emit a registered root schema as a self-contained validator module.

    The module's `validate(instance) -> bool` agrees with `Engine.evaluate`
    on every instance. Raises `StandaloneUnsupportedError` when the plan
    has any interpreted unit or the engine's regex backend is not `re`.
    `max_dynamic_winners` is the planner's specialization cap (see
    `compile_validator`).
    """
    if engine.regex_cache.backend != "re":
        raise StandaloneUnsupportedError(
            f"standalone modules use the `re` backend; the engine uses "
            f"{engine.regex_cache.backend!r}"
        )
    registry = engine.schemas.snapshot()
    plan = build_plan_over(
        registry, schema_uri, max_dynamic_winners=max_dynamic_winners
    )
    if plan.targets:
        explanation = explain_compilation(plan)
        causes = ", ".join(f"{cause}: {n}" for cause, n in explanation.causes.items())
        raise StandaloneUnsupportedError(
            "the schema needs the interpreter at evaluation time "
            f"({causes}); interpreted units: " + ", ".join(explanation.interpreted_keys)
        )
    serialized = serialize_plan(plan, registry, DEFAULT_FLAGS)
    budget = engine.max_depth if max_depth is None else max_depth
    prologue: list[ast.stmt] = [
        ast.Import(names=[ast.alias(name="re", asname=None)]),
        _import_from("json_schema_engine.core.errors", [(e.DEPTH_ERROR, None)]),
        _import_from(
            "json_schema_engine.core.json_model",
            [
                ("has_duplicate_items", e.H_DUP),
                ("is_multiple_of", e.H_MOF),
                ("json_equal", e.H_EQ),
            ],
        ),
        _import_from(
            "json_schema_engine.core.coverage",
            [("fold_index_coverage", e.H_COVI), ("fold_name_coverage", e.H_COVN)],
        ),
        e.assign(e.H_MAXD, e.const(budget)),
        e.function(
            e.H_DEEP,
            [],
            [
                ast.Raise(
                    exc=e.call(
                        e.load(e.DEPTH_ERROR),
                        e.const(f"schema application exceeds max_depth ({budget})"),
                    ),
                    cause=None,
                )
            ],
        ),
    ]
    for name, source in serialized.regexes:
        translated, flags = _pattern_source(engine, source)
        prologue.append(
            e.assign(
                name,
                e.call(
                    e.attr(e.load("re"), "compile"), e.const(translated), e.const(flags)
                ),
            )
        )
    prologue.extend(_format_imports(engine, serialized.formats))
    module = assemble(prologue, serialized)
    return HEADER + ast.unparse(module) + "\n"


def _format_imports(
    engine: Engine, formats: tuple[tuple[str, str], ...]
) -> list[ast.stmt]:
    """`from <module> import <predicate> as fmtN` for every asserted format.

    The predicate is imported by the table entry's `import_path`, checked
    here (by string, never by importing the formats package into the
    compiler) to resolve to the very function the table holds.
    """
    if not formats:
        return []
    table = engine.formats
    assert table is not None  # a plan asserts formats only through a table
    by_module: dict[str, list[tuple[str, str | None]]] = {}
    for hoisted, name in formats:
        definition = table[name]
        path = definition.import_path
        if path is None:
            raise StandaloneUnsupportedError(
                f"format {name!r} has no import path; a standalone module can "
                "only import predicates that name one"
            )
        module_name, _, attribute = path.partition(":")
        resolved = getattr(importlib.import_module(module_name), attribute, None)
        if resolved is not definition.test:
            raise StandaloneUnsupportedError(
                f"format {name!r}: import path {path!r} does not resolve to the "
                "table's predicate"
            )
        by_module.setdefault(module_name, []).append((attribute, hoisted))
    return [_import_from(module, names) for module, names in sorted(by_module.items())]
